### ISSUE TITLE
Analytics not working properly

### ISSUE THREAD

**Issue by rodrigopavezi** [Rise-Vision/risevision-documentation#110]
@toddhemme: 
"@rodrigopavezi one other thing I noticed is Google Analytics isn't reporting page URLs for help.risevision.com and developer.risevision.com. Here's what I see http://www.screencast.com/t/buEw98IA63f6. I'm not sure what analytics uses to pull in the URL. I've never seen this issue before. Do you have any ideas what is missing?"

**Comment by ByronDarlison** [comment]
@rodrigopavezi @toddhemme this issue is closed right? @ghislaineguerin can you confirm as well? Thanks

**Comment by rodrigopavezi** [comment]
@ByronDarlison I don't have access to google analytics anymore. I will leave with @toddhemme or @ghislaineguerin to verify that. cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi okay. @ghislaineguerin can you confirm?

**Comment by ghislaineguerin** [comment]
@ByronDarlison this is working now

**Comment by ByronDarlison** [comment]
Thanks
