### ISSUE TITLE
Meta tags not working for each page

### ISSUE THREAD

**Issue by rodrigopavezi** [Rise-Vision/risevision-documentation#111]
@toddhemme:
"@rodrigopavezi the meta doesn't seem to be populating for each page. Can you take a look at this when you get a chance?"

"@toddhemme1 I see the issue. The problem is that this is not a simple thing to fix. Currently crawlers do not handle javascript. So there needs to be a pre-rendering phase.

What happens is that angular changes the DOM but keeps the html head section unchanged while switching between pages. I have added code so the meta tags elements get also changed. We can see that it works because the title gets changed. Just check the title on the tab of the browser for each page.

To make it work for crawlers we will have to introduce a prerender such as this tool https://prerender.io/. With it comes major changes to how we host the application. We cannot host it anymore on github pages. We will have to change it to an Apache or a Nginx server. Then we can use their service or run it ourselves for free.

@byrondarlison please have a look at the above comment. Is there anybody else in the company who would have experience with what we are talking about here?

Thanks."

**Comment by ByronDarlison** [comment]
@rodrigopavezi this is closed now right? Thanks

**Comment by rodrigopavezi** [comment]
@ByronDarlison that is right. it is fixed now. cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi thanks
