### ISSUE TITLE
Gulp Task Error

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/risevision-documentation#282]
I am trying to test locally. After cloning the repo I run gulp in terminal per the read me and get the following error when it tries to start the jekyl build http://www.screencast.com/t/A55f6sse

@RV-Adrian has also expeirenced.

@rodrigopavezi FYI not sure if you were aware whats going on.

**Comment by rodrigopavezi** [comment]
@mmeiers do you have bundler installed? If not, you will have to run 'gem install bundler'. cheers

**Comment by ByronDarlison** [comment]
@mmeiers @rodrigopavezi is this still open?

**Comment by mmeiers** [comment]
@ByronDarlison @rodrigopavezi I believe I found a workaround without having to run the entire build. I will give it a try sometime today and report back.

**Comment by ByronDarlison** [comment]
@mmeiers any conclusion on this?

**Comment by mmeiers** [comment]
@rodrigopavezi @ByronDarlison Yes Rodrigo's suggestion solved the error in the screen shot.
This can be closed.

**Comment by ByronDarlison** [comment]
Okay. Thanks @mmeiers
