### ISSUE TITLE
Navigation bar does not function on mobile/smaller resolutions.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/risevision-documentation#306]
**How to recreate**
1. Navigate to help.risevision.com
2. Narrow the browser window to 1136px or less width

**What happens**
The navigation bar on the left of the page disappears, a dropdown navigation bar appears. The dropdown navigation bar is blank and cannot be used for navigation.

**What should happen**
The navigation bar should populate with the same content that is on the left navigation bar. 

**Video**
http://www.screencast.com/t/aa8RQGL93aH

**Comment by ezequielc** [comment]
@btfrise A fix has been deployed. Could you verify and close the issue? Thanks!

**Comment by btfrise** [comment]
Looks good, thanks @ezequielc !
